# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("f_fond_de_carte works", {
  expect_true(inherits(f_fond_de_carte, "function")) 
})
