# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("ajoute_coursdeau works", {
  expect_true(inherits(ajoute_coursdeau, "function")) 
})
