# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.


test_that("percentile_dce_par_station_multi calcule bien percentile DCE + N", {

  analyses_test <- tibble::tibble(
    station = c("A","A","B","B","B","C"),
    param = c("1302","1302","1302","8727","8727","1302"),
    resultat = c(1,5,4,8,12,7)
  )

  res <- percentile_dce_par_station_multi(
    analyses_test,
    cd_parametres = c("1302","8727"),
    type = 0.9,
    station_col = "station",
    param_col = "param",
    result_col = "resultat"
  )

  # Vérification de N pour station B, param 8727 (8,12)
  expect_equal(
    res$N[res$station == "B" & res$param == "8727"],
    2
  )

  # Vérification percentile Hazen B-8727 : valeurs 8,12 → rang = 2 → 12
  expect_equal(
    res$percentile_dce[
      res$station == "B" & res$param == "8727"
    ],
    12
  )

  # Test type colonne résultat incorrect
  bad <- analyses_test
  bad$resultat <- as.character(bad$resultat)
  expect_error(
    percentile_dce_par_station_multi(
      bad,
      cd_parametres = "1302",
      station_col = "station",
      param_col = "param",
      result_col = "resultat"
    )
  )
})

