# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("analyse_fonctions_pesticides works", {
  expect_true(inherits(analyse_fonctions_pesticides, "function")) 
})
