# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.


test_that("percentile_dce_par_station_multi fonctionne avec Hazen et colonnes paramétrables", {

  analyses_test <- tibble::tibble(
    station = c("A","A","B","B","B","C"),
    param = c("1302","1302","1302","8727","8727","1302"),
    resultat = c(1,5,4,8,12,7)
  )

  res <- percentile_dce_par_station_multi(
    analyses_test,
    cd_parametres = c("1302","8727"),
    type = 0.9,
    station_col = "station",
    param_col = "param",
    result_col = "resultat"
  )

  # Vérification Hazen pour B-8727 : valeurs 8, 12 → rang = 2
  expect_equal(
    res$percentile_dce[
      res$station == "B" & res$param == "8727"
    ],
    12
  )

  # Test des types invalides
  analyses_bad <- analyses_test
  analyses_bad$resultat <- as.character(analyses_bad$resultat)
  expect_error(
    percentile_dce_par_station_multi(analyses_bad,
      cd_parametres = "1302",
      result_col = "resultat"
    )
  )

})

