# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("importe_ref_pestibase works", {
  expect_true(inherits(importe_ref_pestibase, "function")) 
})
