# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("calcule_somme_pesticides works", {
  expect_true(inherits(calcule_somme_pesticides, "function")) 
})
