# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fiche_usages_pesticides works", {
  expect_true(inherits(fiche_usages_pesticides, "function")) 
})
