# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("percentile_dce fonctionne selon la méthode de Hazen", {

  # jeu simple
  x <- c(1, 3, 8, 10, 12)  # n=5

  # 90e percentile Hazen : rang = (5*0.9)+0.5 = 5 -> arrondi = 5
  expect_equal(percentile_dce(x, type = 0.9), 12)

  # 10e percentile Hazen : rang = (5*0.1)+0.5 = 1 -> arrondi =1
  expect_equal(percentile_dce(x, type = 0.1), 1)

  # gestion NA
  x2 <- c(4, 6, 9, NA, 3)
  expect_equal(percentile_dce(x2, type = 0.9, na.rm = TRUE),
               percentile_dce(c(4, 6, 9, 3), type = 0.9))

  # erreurs attendues
  expect_error(percentile_dce(c(1, NA), type = 0.9, na.rm = FALSE))
  expect_error(percentile_dce(numeric(0), type = 0.9))
})
