# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("heatmap_substances works", {
  expect_true(inherits(heatmap_substances, "function")) 
})
