# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' analyse_fonctions_pesticides
#' 
#' Analyse des fonctions des substances pesticides
#'
#' Cette fonction permet d'analyser les fonctions des substances pesticides quantifiées
#' à partir d'un jeu de données analytique et d'une table de référence des pesticides.
#' Elle filtre les résultats selon un code de remarque analytique, joint les données
#' aux fonctions des substances, puis génère un graphique ggplot représentant la
#' répartition des fonctions en pourcentage de la concentration totale mesurée.
#'
#' @param data Data frame contenant les résultats analytiques, incluant les colonnes
#' correspondant aux codes de remarque et de paramètre.
#' @param code_remarque Nom de la colonne dans `data` correspondant au code de remarque analytique.
#' Par défaut `"CdRqAna"`.
#' @param code_parametre Nom de la colonne dans `data` correspondant au code du paramètre.
#' Par défaut `"CdParametre"`.
#' @param liste_pesticides Data frame issu de la fonction `importe_ref_pestibase`, contenant
#' les colonnes `SA_CodeSANDRE`, `function_bzh` et `function_fr` pour l'association des fonctions.
#'
#' @return Un objet `ggplot` représentant la répartition des fonctions des substances
#' pesticides quantifiées.
#'
#' @export
#' @examples
#'
#' ref_pestibase <- importe_ref_pestibase()
#'
#' data <- data.frame(
#'    DatePrel = Sys.Date() + rep(sort(sample(1:500, 10)), 3),
#'    RsAna = round(runif(60, 0, 0.5), 2),
#'    LqAna = 0.1,
#'    CdStationMesureEauxSurface = c("A", "B", "C"),
#'    CdParametre = sample(ref_pestibase$liste_phytos_autorises$SA_CodeSANDRE,
#'                         size=10,
#'                         replace=TRUE),
#'    CdUniteMesure = "133"
#'  )
#'  data$CdRqAna <- ifelse(data$RsAna >= data$LqAna, "1", "10")
#'
#' analyse_fonctions_pesticides(data, 
#'                              code_remarque="CdRqAna",
#'                              code_parametre="CdParametre",
#'                              liste_pesticides=ref_pestibase$liste_phytos_autorises)
#'
#'
analyse_fonctions_pesticides <- function(data, 
                                         code_remarque = "CdRqAna",
                                         code_parametre = "CdParametre",
                                         liste_pesticides) {
  # Vérifications des paramètres
  if (!is.data.frame(data)) {
    stop("Le paramètre 'data' doit être un data.frame contenant les résultats analytiques.")
  }
  if (!is.character(code_remarque) || length(code_remarque) != 1) {
    stop("Le paramètre 'code_remarque' doit être une chaîne de caractères correspondant au nom d'une colonne de 'data'.")
  }
  if (!is.character(code_parametre) || length(code_parametre) != 1) {
    stop("Le paramètre 'code_parametre' doit être une chaîne de caractères correspondant au nom d'une colonne de 'data'.")
  }
  if (!(code_remarque %in% names(data))) {
    stop(paste0("La colonne '", code_remarque, "' est absente du data.frame 'data'."))
  }
  if (!(code_parametre %in% names(data))) {
    stop(paste0("La colonne '", code_parametre, "' est absente du data.frame 'data'."))
  }
  if (!("RsAna" %in% names(data))) {
    stop("La colonne 'RsAna' est requise dans 'data' pour calculer les concentrations.")
  }
  if (!is.data.frame(liste_pesticides)) {
    stop("Le paramètre 'liste_pesticides' doit être un data.frame issu de la fonction 'importe_ref_pestibase'.")
  }
  required_cols <- c("SA_CodeSANDRE", "function_bzh", "function_fr")
  missing_cols <- setdiff(required_cols, names(liste_pesticides))
  if (length(missing_cols) > 0) {
    stop(paste("Les colonnes suivantes sont manquantes dans 'liste_pesticides' :", paste(missing_cols, collapse = ", ")))
  }

  # Traitement
  data$CdRqAna <- data[[code_remarque]]
  data$CdParametre <- data[[code_parametre]]

  data <- data %>%
    dplyr::filter(CdRqAna == "1") %>%
    dplyr::left_join(liste_pesticides, by = c("CdParametre" = "SA_CodeSANDRE")) %>%
    dplyr::mutate(function_finale = dplyr::coalesce(function_bzh, function_fr)) %>%
    dplyr::mutate(function_finale = ifelse(is.na(function_finale), "Indéterminé", function_finale)) %>%
    dplyr::mutate(function_finale = ifelse(function_finale=="regulateur", "Régulateur", function_finale)) %>%
    dplyr::group_by(function_finale) %>%
    dplyr::summarise(total_quantifie = sum(RsAna, na.rm = TRUE)) %>%
    dplyr::mutate(pourcentage = total_quantifie / sum(total_quantifie, na.rm = TRUE) * 100) %>%
    dplyr::arrange(desc(pourcentage))

  g <- ggplot2::ggplot(data, ggplot2::aes(x = reorder(function_finale, pourcentage), y = pourcentage)) +
    ggplot2::geom_bar(stat = "identity", fill = "steelblue") +
    ggplot2::coord_flip() +
    ggplot2::labs(title = "Fonctions des substances quantifiées",
                  subtitle = "% de la concentration totale mesurée",
                  x = "", y = "%") +
    ggplot2::theme_minimal()

  return(g)
}


