# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Arrondi classique (arrondi commercial)
#'
#' Cette fonction effectue un arrondi classique ("à la française") d'un nombre
#' à un certain nombre de décimales.  
#'
#' L'arrondi suit les règles :
#' \itemize{
#'   \item si la partie décimale est < 0.5 : arrondi par défaut,
#'   \item si la partie décimale est > 0.5 : arrondi par excès,
#'   \item si la partie décimale est = 0.5 : arrondi à l'entier supérieur
#'         (conformément aux usages français).
#' }
#'
#' @param nb Nombre réel à arrondir.
#' @param digits Nombre entier de décimales (0 par défaut).
#'
#' @return Le nombre arrondi selon la méthode classique.
#'
#' @examples
#' arrondi(3.14159, digits = 2)   # 3.14
#' arrondi(2.145, digits = 2)     # 2.15
#' arrondi(-2.145, digits = 2)    # -2.15 (règle symétrique)
#'
#' # Exemple : arrondi classique
#' arrondi(3.14159, digits = 2)   # 3.14
#' arrondi(3.145, digits = 2)     # 3.15
#' arrondi(-3.145, digits = 2)    # -3.15
#'
#' # Exemple avec digits = 0
#' arrondi(2.7)   # 3
#' arrondi(-2.7)  # -3
#' @export
arrondi <- function(nb, digits = 0) {

  # Vérifications des arguments
  if (!is.numeric(digits)) {
    stop("digits doit être un nombre")
  }
  if (digits %% 1 != 0) {
    stop("digits doit être un entier")
  }
  if (digits < 0) {
    stop("digits doit être un entier positif")
  }

  # Mise à l'échelle
  nb_scaled <- nb * (10 ^ digits)

  # Arrondi classique
  if (nb_scaled >= 0) {
    if (abs(nb_scaled - floor(nb_scaled)) < 0.5) {
      nb_scaled <- floor(nb_scaled)
    } else {
      nb_scaled <- floor(nb_scaled) + 1
    }
  } else {
    if (abs(nb_scaled - floor(nb_scaled)) <= 0.5) {
      nb_scaled <- floor(nb_scaled)
    } else {
      nb_scaled <- floor(nb_scaled) + 1
    }
  }

  # Retour à l'échelle d'origine
  nb_scaled <- nb_scaled / (10 ^ digits)
  return(nb_scaled)
}
