# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' f_fond_de_carte
#' 
#' Fonction pour charger un fon de carte openstreetmap correspondant à l'emprise
#' d'un objet sf
#' 
#' @param shp = objet sf
#' @param zoom = niveau de zoom openstreetmap (paramètre facultatif)
#' 
#' @return
#' un ggplot avec le fond de carte openstreetmap correspondant à l'emprise de
#' l'objet en entrée
#' 
#' @export
#' @examples
#'
#'    triangle_sf <- sf::st_sf(
#'         geometry = sf::st_sfc(
#'           sf::st_polygon(list(rbind(
#'             c(-1.6794, 48.1147),  # Rennes
#'             c(-1.2100, 48.1230),  # Vitré
#'             c(-1.5025, 47.6833),  # Derval
#'             c(-1.6794, 48.1147)   # Retour à Rennes
#'           )))
#'         ),
#'         crs = 4326
#'       )
#'
#' f_fond_de_carte(triangle_sf, zoom=9)
f_fond_de_carte <- function(shp, zoom = NULL) {
  bbox <- sf::st_bbox(sf::st_transform(shp, 4326))
  
  # Charger le fond de carte OpenStreetMap avec maptiles
  if (is.null(zoom)) {
    sa_map <- maptiles::get_tiles(bbox, provider = "OpenStreetMap")
  } else {
    sa_map <- maptiles::get_tiles(bbox, zoom = zoom, provider = "OpenStreetMap")
  }
  
  # Recadrer le raster à l'emprise de shp
  sa_map_cropped <- raster::crop(sa_map, 
                                 raster::extent(bbox["xmin"], 
                                                bbox["xmax"], 
                                                bbox["ymin"], 
                                                bbox["ymax"]))
  
  # Convertir le raster en objet ggplot
  sa_map2_plt <- ggplot2::ggplot() +
    ggspatial::layer_spatial(sa_map_cropped) +
    ggplot2::coord_sf(xlim = c(bbox["xmin"], bbox["xmax"]), 
                      ylim = c(bbox["ymin"], bbox["ymax"]), 
                      expand = FALSE)
  
  shp <- sf::st_transform(shp, 4326)
  
  sa_map2_plt <- sa_map2_plt +
    ggplot2::geom_sf(data = shp, 
            fill = "transparent", 
            color = "black", 
            size = 1, 
            inherit.aes = FALSE)+
     theme_minimal() +
    theme(axis.text = element_blank(), # masque les valeurs des axes
          axis.ticks = element_blank(), # masque les ticks
          axis.title = element_blank()) # masque les titres des axes
  
  return(sa_map2_plt)
}

