# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' f_graph_pluviometrie
#'
#' Cette fonction génère un graphique de la pluviométrie de la date et des 4 
#' jours précédents. 
#' La pluviométrie est évaluée au plus prêt du centroïde de shp_territoire.
#' S'il y a une ou plusieurs stations Météo France dans le shp_territoire, les 
#' valeurs affichées sont celles de la station la plus proche du centroïde.
#' 
#' S'il n'y a pas de station Météo France dans l'emprise de shp_territoire, 
#' alors les précipitations sont estimées par krigeage.
#'
#' @param shp_territoire : objet sf pour lequel on veut les informations de 
#' pluviométrie
#' @param dateprel : date du dernier jour du graphique
#' @param con : connexion vers la base de données météo
#'
#' @return
#' Objet ggplot avec un histogramme sur les précipitations des 5 derniers jours.
#' @export
#'
#' @examples
#'
#' if (interactive()) {
#'   config_path <- "C://workspace//gwilenalim//yaml//config.yml"
#'   if (file.exists(config_path)) {
#'     config <- yaml::read_yaml(config_path)
#'     con <- tryCatch({
#'       DBI::dbConnect(
#'         RPostgres::Postgres(),
#'         host = config$host,
#'         port = config$port,
#'         user = config$user,
#'         password = config$password,
#'         dbname = config$dbname
#'       )
#'     }, error = function(e) NULL)
#'     
#'     if (!is.null(con)) {
#'       triangle_sf <- sf::st_sf(
#'         geometry = sf::st_sfc(
#'           sf::st_polygon(list(rbind(
#'             c(-1.6794, 48.1147),  # Rennes
#'             c(-1.2100, 48.1230),  # Vitré
#'             c(-1.5025, 47.6833),  # Derval
#'             c(-1.6794, 48.1147)   # Retour à Rennes
#'           )))
#'         ),
#'         crs = 4326
#'       )
#'       
#'       f_graph_pluviometrie(triangle_sf, date = as.Date("2025-09-10"), con)
#'       DBI::dbDisconnect(con)
#'     } else {
#'       message("Connexion à la base impossible, exemple non exécuté.")
#'     }
#'   } else {
#'     message("Fichier de configuration introuvable.")
#'   }
#' }
#'
#'
#'
f_graph_pluviometrie<-function(shp_territoire,
                               dateprel, 
                               con)
{
  pluie <- meteo4Vilaine::precipitations_par_zone(
    sf_objet=shp_territoire,
    date_debut=dateprel-4,
    date_fin=dateprel,
    con
  )
  
  pluie$fill_color<-ifelse(pluie$source=="donnée interpolée", 
                           "interpolation", 
                           "Météo France")
  
  g<-ggplot2::ggplot(pluie,
         ggplot2::aes(date,
             y=precipitation_mm,
             fill=fill_color)) +
    ggplot2::geom_bar(stat="identity",
             color="blue") +
    ggplot2::scale_fill_manual(
      name="Station météo",
      values = c("interpolation"="white",
                 "Météo France"="blue")) +
    ggplot2::scale_x_date(date_labels="%d/%m/%Y") +
    ggplot2::labs(x="",
         y="mm/jour",
         title="Précipitations journalières") +
    ggplot2::theme_minimal() +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle=45, hjust=1))
  
  return(g)
  
}
