# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' heatmap_substances
#' 
#' Génère une heatmap des substances quantifiées au-delà d’un seuil
#'
#' Cette fonction crée une heatmap des concentrations de substances (ex. : 
#' pesticides)
#' mesurées dans différentes stations, en mettant en évidence celles dont les 
#' valeurs dépassent un seuil donné.
#' Le gradient de couleur est personnalisable selon les seuils définis.
#'
#' @param df Data frame contenant les résultats d’analyses.
#' @param col_station Nom de la colonne contenant les codes des stations. 
#' Défaut : `"CdStationMesureEauxSurface"`.
#' @param col_param Nom de la colonne contenant les noms des substances ou 
#' paramètres. Défaut : `"NomParametre"`.
#' @param col_result Nom de la colonne contenant les résultats d’analyse. 
#' Défaut : `"RsAna"`.
#' @param col_remarque Nom de la colonne contenant les codes de remarque. 
#' Défaut : `"CdRqAna"`.
#' @param titre Titre du graphique. Défaut : `"Substances quantifiées au-delà 
#' du seuil"`.
#' @param seuil_bas Seuil inférieur du gradient de couleur (début du jaune). 
#' Défaut : `0.1`.
#' @param seuil_haut Seuil supérieur du gradient de couleur (début du rouge). 
#' Défaut : `2`.
#' @param chiffres_significatifs Nombre de chiffres significatifs à afficher 
#' dans les cases. Défaut : `2`.
#' @param police_etiquettes Taille de la police de caractères dans les 
#' étiquettes. Défaut : `6`.
#' @param police_axes Taille de la police de caractères pour les 
#' axes. Défaut : `12`.
#' @param  type_palette : palette de couleur "discrete" (par défaut) ou  
#' "continue" 
#'
#' @return Un objet ggplot représentant la heatmap.
#' 
#' @export
#' @examples
#'
#'
#' # Définition des stations
#' stations <- c("04123456", "04345678", "04987654", "04246810")
#'
#' # Définition des pesticides courants en France
#' pesticides <- c(
#'   "Glyphosate", "Atrazine", "Métolachlore", "S-métolachlore", "Terbuthylazine",
#'   "Chlorotoluron", "Isoproturon", "Diuron", "Pendiméthaline"
#' )
#'
#' # Génération du jeu de données
#' set.seed(123)  # Pour reproductibilité
#' df_fictif <- expand.grid(CdStationMesureEauxSurface = stations, NomParametre = pesticides) %>%
#'   dplyr::rowwise() %>%
#'   dplyr::mutate(
#'     RsAna = round(runif(1, 0, 1), 2),
#'     CdRqAna = ifelse(RsAna <= 0.02, "0", "1")
#'   ) %>%
#'   dplyr::ungroup()
#'
#'
#' heatmap_substances(
#'   df = df_fictif,
#'   titre = "Substances quantifiées > 0.1 µg/L - palette continue",
#'   seuil_bas = 0.1,
#'   seuil_haut = 2,
#'   chiffres_significatifs=2,
#'   type_palette="continue"
#' )
#'
#' heatmap_substances(
#'   df = df_fictif,
#'   titre = "Substances quantifiées > 0.1 µg/L - palette discrete",
#'   seuil_bas = 0.1,
#'   seuil_haut = 2,
#'   chiffres_significatifs=2,
#'   type_palette="discrete"
#' )

heatmap_substances <- function(
  df,
  col_station = "CdStationMesureEauxSurface",
  col_param = "NomParametre",
  col_result = "RsAna",
  col_remarque = "CdRqAna",
  titre = "Substances quantifiées au-delà du seuil",
  seuil_bas = 0.1,
  seuil_haut = 2,
  chiffres_significatifs = 2,
  police_etiquettes = 6,
  police_axes = 12,
  type_palette = "discrete" # "continue" ou "discrete"
) {
  library(dplyr)
  library(ggplot2)
  library(scales)

  # Étape 1 : filtrer les substances significatives
  substances_significatives <- df %>%
    filter(.data[[col_remarque]] == "1", .data[[col_result]] > seuil_bas) %>%
    distinct(.data[[col_param]])

  # Étape 2 : récupérer les données pertinentes
  donnees_heatmap <- df %>%
    filter(.data[[col_param]] %in% substances_significatives[[col_param]] & .data[[col_remarque]] == "1")

  # Étape 3 : définir la palette de couleurs
  if (type_palette == "continue") {
    palette_couleur <- scale_fill_gradientn(
      colours = c("lightblue", "yellow", "red", "purple"),
      values = rescale(c(0, seuil_bas, seuil_haut, max(max(donnees_heatmap[[col_result]], na.rm = TRUE), 2 * seuil_haut))),
      name = "(µg/L)"
    )
  } else if (type_palette == "discrete") {
    # Créer des classes de concentration
    donnees_heatmap <- donnees_heatmap %>%
      mutate(classe_concentration = cut(.data[[col_result]],
        breaks = c(0, seuil_bas, seuil_haut, Inf),
        labels = c(paste0("≤ ", seuil_bas), paste0(seuil_bas, " - ", seuil_haut), paste0("> ", seuil_haut))
      ))

   palette_couleur <- scale_fill_manual(
  values = setNames(
    c("lightblue", "orange", "red"),
    c(paste0("≤ ", seuil_bas),
      paste0(seuil_bas, " - ", seuil_haut),
      paste0("> ", seuil_haut))
  ),
  name = "(µg/L)"
)

  }

  # Étape 4 : créer le graphique
  g <- ggplot(donnees_heatmap,
              aes(x = .data[[col_station]],
                  y = .data[[col_param]],
                  fill = if (type_palette == "continue") .data[[col_result]] else .data[["classe_concentration"]])) +
    geom_tile(color = "white") +
    geom_text(aes(label = round(.data[[col_result]], chiffres_significatifs)),
              size = police_etiquettes,
              color = "black") +
    palette_couleur +
    labs(title = titre, x = "", y = "") +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = police_axes),
      axis.text.y = element_text(size = police_axes)
    )

  return(g)
}
