# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' importe_ref_pestibase
#' 
#' Import du référentiel Pestibase de l'OEB
#'
#' Cette fonction télécharge et traite le référentiel des substances actives 
#' (pesticides) publié par l'Observatoire de l'Environnement en Bretagne (OEB).
#' Elle retourne une liste d'objets R correspondant aux différentes catégories 
#' de substances : phytosanitaires, biocides, métabolites, etc...
#'
#' @param url URL du fichier CSV à importer. Par défaut, l'URL pointe vers le 
#' fichier complet du référentiel sur le portail data.bretagne-environnement.fr.
#'
#' @return Une liste nommée contenant les éléments suivants :
#' \describe{
#'   \item{liste_phytos}{Substances identifiées comme phytosanitaires 
#'   (autorisées ou non).}
#'   \item{liste_phytos_autorises}{Phytosanitaires actuellement autorisés, 
#'   y compris les variantes associées.}
#'   \item{liste_phytos_non_autorises}{Phytosanitaires ayant été autorisés mais 
#'   ne l'étant plus.}
#'   \item{liste_metabolites}{Ensemble des métabolites de pesticides 
#'   (pertinents ou non).}
#'   \item{liste_metabolites_pertinents}{Sous-ensemble des métabolites jugés 
#'   pertinents.}
#'   \item{liste_metabolites_non_pertinents}{Sous-ensemble des métabolites jugés
#'    non pertinents.}
#'   \item{liste_biocides}{Substances identifiées comme biocides.}
#'   \item{liste_pesticides}{Ensemble des substances identifiées comme 
#'   pesticides ou métabolites.}
#' }
#'
#' @details
#' - La fonction effectue des vérifications sur la structure du fichier et 
#' envoie une alerte par mail en cas d'erreur.
#' - Les variantes de substances autorisées sont intégrées à la liste des 
#' phytosanitaires autorisés via les codes SANDRE.
#'
#' @examples
#' \dontrun{
#'   ref_pestibase <- importe_ref_pestibase()
#'   names(ref_pestibase)
#' }
#'
#' base_pesticides<-importe_ref_pestibase()
#'
#' head(base_pesticides)
#' @export
importe_ref_pestibase <- function(url=NULL){

  if(is.null(url))
{url<-"https://data.bretagne-environnement.fr/data-fair/api/v1/datasets/qa4yo6sypr0x07-mj80iqk7a/data-files/oeb_referentiel_substances_actives-full.csv"}
  
# Charger le fichier CSV dans la variable new_ref_oeb
new_ref_oeb0 <- tryCatch(
  {
    readr::read_csv(url,
             show_col_types =FALSE)
  },
  error = function(e) {
    message("Erreur : impossible de charger le référentiel OEB depuis l'URL fournie.")
    stop("Chargement interrompu : l'URL de l'OEB ne répond pas ou est invalide.")
  }
)

new_ref_oeb<-new_ref_oeb0%>%subset(!is.na(id) & !is.na(id_sandre))
new_ref_oeb$SA_CodeSANDRE<-new_ref_oeb$id_sandre

new_ref_oeb<- tryCatch(
  {
    new_ref_oeb %>% select(
      id,
      id_sandre,
      id_cas,
      name_fr,
      SA_CodeSANDRE,
      has_metabolite,
      dw_pertinence_status,
      has_authorized_oepp_culture,
      has_removed_authorized_oepp_culture,
      function_fr,
      function_bzh,
      has_variant,
      has_metabolite,
      biocidal_product_type,
      list_parent_measures,
      is_ref_ppp,
      is_bnvd,
      is_ref_biocid,
      vmax,
      is_edc_list1,
      aa_eqs_dw,
      aa_eqs,
      aa_eqs_mac,
      aa_eqs_eco_psee,
      log_biodeg_halflife,
      pc_log_henry,
      pc_log_koc, 
      pnec,
      eu_ppp_status,
      eu_ppp_approval_date,
      eu_ppp_expiry_date,
      eu_ppp_legislation,
      eu_biocid_status,
      eu_biocid_approval_date,
      eu_biocid_expiry_date,
      is_neonicotinoid
    )
    
  },
  error = function(e) {
     message("Erreur lors de la tentative de chargement du referentiel. Le 
             fichier telecharge depuis l'OEB ne contient pas les noms de 
             colonnes attendus.")
    stop("Les colonnes du referentiel pesticide OEB ne sont pas celles attendues")
    }
)

  new_ref_oeb <- new_ref_oeb %>%
    dplyr::mutate(SA_CodeSANDRE = as.character(SA_CodeSANDRE))%>%
    dplyr::mutate(function_finale = ifelse(!is.na(function_bzh), 
                                           function_bzh, 
                                           function_fr))

# LISTE DES METABOLITES
# Extraire les ids des deux tableaux
id_metabolites <- unlist(stringr::str_split(new_ref_oeb$has_metabolite, "\\|"))
liste_metabolites <- new_ref_oeb %>%   
  filter(id %in% id_metabolites)%>% 
  dplyr::mutate(type="métabolites")


# listes phytos autorisés ou interdits
liste_phytos<-new_ref_oeb%>%
  subset(is_ref_ppp==1 | is_bnvd==1)%>%
  mutate(type="phytosanitaires")
  
 # On exclu de la liste des métabolites les substances qui sont également des phytos (ex. 2,4-D) 
  liste_metabolites<-liste_metabolites%>%
  subset(!(id%in%liste_phytos$id))
  
  
liste_metabolites_non_pertinents<-liste_metabolites%>%
  subset(dw_pertinence_status=="Non pertinent")%>%
  dplyr::mutate(type="métabolites non pertinents")


liste_metabolites_pertinents<-liste_metabolites%>%
  subset(!(id%in%liste_metabolites_non_pertinents$id))%>%
  dplyr::mutate(type="métabolites pertinents")

# liste phytos autorisés
liste_phytos_autorises<-liste_phytos%>%
  subset(!is.na(has_authorized_oepp_culture))

#on ajoute les paramètres qui intègrent la mesure de phytos autorisés (ex. Diméthénamide intègre diméthénamide P)
# Extraction des codes SANDRE
codes_sandre <- liste_phytos_autorises %>%
  subset(!is.na(list_parent_measures))%>%
  mutate(codes = stringr::str_extract_all(list_parent_measures, "sandre\\s*:\\s*(\\d{4})")) %>%
  pull(codes) %>%
  unlist() %>%
  stringr::str_extract("\\d{4}") %>%
  unique()

variants <- new_ref_oeb%>%
  subset(id_sandre %in% codes_sandre)%>%
  mutate(type="phytos autorisés")

liste_phytos_autorises<-rbind(liste_phytos_autorises,variants)

liste_phytos_autorises<-liste_phytos_autorises%>%
  mutate(type="phytos autorisés")%>%
  unique

# liste phytos non autorisés
liste_phytos_non_autorises<-liste_phytos%>%
 subset(!(id%in%liste_phytos_autorises$id))%>%
  mutate(type="phytos non autorisés")%>%
  unique

# liste pesticides
liste_pesticides<-new_ref_oeb %>%
  mutate(type="pesticides et métabolites")%>%
  unique

#liste biocides
liste_biocides<-new_ref_oeb %>%
  subset(is_ref_biocid==1)%>%
  mutate(type="biocides")

# agrégation
liste_des_listes_pesticides<-list(liste_phytos=liste_phytos,
                                  liste_phytos_autorises=liste_phytos_autorises,
                                  liste_phytos_non_autorises=liste_phytos_non_autorises,
                                  liste_metabolites=liste_metabolites,
                                  liste_metabolites_pertinents=liste_metabolites_pertinents,
                                  liste_metabolites_non_pertinents=liste_metabolites_non_pertinents,
                                  liste_biocides=liste_biocides,
                                  liste_pesticides=liste_pesticides)  
  
  
  return(liste_des_listes_pesticides)
  
}
