# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calcul du percentile DCE (Hazen) par station pour plusieurs paramètres
#'
#' Cette fonction applique la méthode de Hazen (via \code{percentile_dce()})
#' pour calculer un percentile DCE (ex : 0.1 ou 0.9) pour chaque combinaison
#' station × paramètre, dans une table d'analyses au format SANDRE/ROSEAU.
#'
#' Les noms des colonnes utilisées peuvent être paramétrés, avec valeurs par défaut :
#' \itemize{
#'   \item station_col = "CdStationMesureEauxSurface"
#'   \item param_col = "CdParametre"
#'   \item result_col = "RsAna"
#' }
#'
#' Un contrôle strict des types est effectué :
#' \itemize{
#'   \item la colonne station doit être de type caractère ou facteur,
#'   \item la colonne paramètre doit être caractère ou facteur,
#'   \item la colonne résultats doit être numérique.
#' }
#'
#' @param analyses Tibble de résultats analytiques.
#' @param cd_parametres Vecteur de codes paramètres SANDRE à filtrer.
#' @param type Percentile DCE (0.1 ou 0.9).
#' @param station_col Nom de la colonne station (défaut : CdStationMesureEauxSurface).
#' @param param_col Nom de la colonne paramètre (défaut : CdParametre).
#' @param result_col Nom de la colonne résultat (défaut : RsAna).
#'
#' @return Une tibble contenant :
#'   \itemize{
#'     \item station_col
#'     \item param_col
#'     \item percentile_dce
#'   }
#'
#' @examples
#' analyses_test <- tibble::tibble(
#'   CdStationMesureEauxSurface = c("A","A","B","B","B","C"),
#'   CdParametre = c("1302","1302","1302","8727","8727","1302"),
#'   RsAna = c(1,5,4,8,12,7)
#' )
#'
#' percentile_dce_par_station_multi(
#'   analyses_test,
#'   cd_parametres = c("1302","8727"),
#'   type = 0.9
#' )
#'
#'
#'
#' # Exemple d'utilisation avec colonnes par défaut
#'
#' analyses_test <- tibble::tibble(
#'   CdStationMesureEauxSurface = c("A","A","B","B","B","C"),
#'   CdParametre = c("1302","1302","1302","8727","8727","1302"),
#'   RsAna = c(1,5,4,8,12,7)
#' )
#'
#' percentile_dce_par_station_multi(
#'   analyses_test,
#'   cd_parametres = c("1302", "8727"),
#'   type = 0.9
#' )
#'
#' # Exemple avec colonnes personnalisées
#'
#' analyses_custom <- analyses_test |>
#'   dplyr::rename(
#'     station = CdStationMesureEauxSurface,
#'     param = CdParametre,
#'     resultat = RsAna
#'   )
#'
#' percentile_dce_par_station_multi(
#'   analyses_custom,
#'   cd_parametres = c("1302", "8727"),
#'   type = 0.1,
#'   station_col = "station",
#'   param_col = "param",
#'   result_col = "resultat"
#' )
#'
#' @export
percentile_dce_par_station_multi <- function(
    analyses,
    cd_parametres,
    type = 0.9,
    station_col = "CdStationMesureEauxSurface",
    param_col = "CdParametre",
    result_col = "RsAna"
) {

  # Vérification présence colonnes
  required <- c(station_col, param_col, result_col)
  missing <- setdiff(required, names(analyses))
  if (length(missing) > 0) {
    stop("Colonnes manquantes dans 'analyses' : ", paste(missing, collapse = ", "))
  }

  # Vérification types colonne station
  if (!is.character(analyses[[station_col]]) &&
      !is.factor(analyses[[station_col]])) {
    stop("La colonne station ('", station_col, "') doit être de type caractère ou facteur.")
  }

  # Vérification types colonne paramètre
  if (!is.character(analyses[[param_col]]) &&
      !is.factor(analyses[[param_col]])) {
    stop("La colonne paramètre ('", param_col, "') doit être de type caractère ou facteur.")
  }

  # Vérification types colonne résultat
  if (!is.numeric(analyses[[result_col]])) {
    stop("La colonne résultat ('", result_col, "') doit être numérique.")
  }

  # Filtrage des paramètres
  d <- analyses |>
    dplyr::filter(.data[[param_col]] %in% cd_parametres) |>
    dplyr::filter(!is.na(.data[[result_col]]))

  if (nrow(d) == 0) {
    warning("Aucune donnée pour les paramètres fournis.")
    return(tibble::tibble(
      !!station_col := character(),
      !!param_col := character(),
      percentile_dce = numeric()
    ))
  }

  d |>
    dplyr::group_by(.data[[station_col]], .data[[param_col]]) |>
    dplyr::summarise(
      percentile_dce = percentile_dce(.data[[result_col]], type = type, na.rm = TRUE),
      .groups = "drop"
    )
}
