# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calcul du percentile DCE selon la méthode de Hazen
#'
#' Cette fonction calcule un percentile DCE (ex : 0.1 ou 0.9) en appliquant
#' strictement la méthode de Hazen, conformément à l'arrêté ministériel
#' du 25 janvier 2010 modifié relatif à l’évaluation de l’état des eaux.
#'
#' La méthode de Hazen consiste à :
#' \itemize{
#'   \item trier les valeurs croissantes,
#'   \item calculer le rang : \eqn{R = (n * p) + 0.5},
#'   \item appliquer un arrondi à l'entier le plus proche,
#'   \item renvoyer la valeur correspondant au rang R.
#' }
#'
#' @param A Vecteur numérique contenant les valeurs mesurées.
#' @param type Numérique compris entre 0 et 1 (ex : 0.1 ou 0.9).
#' @param na.rm Logique : TRUE pour ignorer les valeurs manquantes.
#'
#' @return Une valeur numérique correspondant au percentile DCE calculé.
#'
#' @examples
#' percentile_dce(c(1, 3, 8, 10, 12), type = 0.9)
#' percentile_dce(c(4, 6, 9, NA, 3), type = 0.1, na.rm = TRUE)
#'
#' vec <- c(2.1, 5.4, 3.3, 8.9, 7.1, 12.5, 7.0, 8.5, 2, 4.8, 17, 19.2, NA)
#' percentile_dce(vec, type = 0.9, na.rm = TRUE)
#' percentile_dce(vec, type = 0.1, na.rm = TRUE)
#' @export
percentile_dce <- function(A, type = 0.9, na.rm = TRUE) {

  # vérification du percentile
  if (!is.numeric(type) || type < 0 || type > 1) {
    stop("type doit être un nombre entre 0 et 1")
  }

  # gestion NA
  if (!na.rm && any(is.na(A))) {
    stop(
      "Le vecteur contient des NA. Utiliser na.rm = TRUE pour les ignorer."
    )
  }

  # retrait des NA
  A <- A[!is.na(A)]

  # sécurité : pas de valeurs
  if (length(A) == 0) {
    stop("Aucune valeur disponible pour calculer un percentile DCE.")
  }

  # méthode de Hazen
  n <- length(A)
  rang <- arrondi((n * type) + 0.5)

  # tri
  B <- sort(A)

  B[rang]
}

